### ISSUE TITLE
Can't find libaudiofile and libtapencoder

### ISSUE THREAD

**Issue by sajattack** [fabzzap/wav-prg#2]
I have libaudiofile and libtapencoder installed, but I get this output:
```
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4555:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5023:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4555:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5023:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused
connect(2) call to /dev/shm/jack-0/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
In order to open WAV files, you need libaudiofile and libtapencoder
```

**Comment by fabzzap** [comment]
Is that Linux? If so, what distribution?
Did you compile it yourself?
libaudiofile is distributed by most major distributions (e.g. it is libaudiofile1 in Ubuntu). Note that, until recently, libaudiotap searched for libaudiofile.so.0 but recent Linux distributions come with libaudiofile.so.1. If you pull the latest libaudiotap, and have libaudiofile.so.1 installed, at least libaudiofile should work. Unfortunately the error message does not specify whether one or both cannot be found, it should be made clearer.

**Comment by sajattack** [comment]
It's Arch Linux with libaudiofile.so.1.0.0 installed from source.

**Comment by fabzzap** [comment]
In that case, pull the latest libaudiotap, recompile it and try again. Until recently, libaudiotap did not try to load libaudiofile.so.1.0.0, the latest commit to it fixes that.

**Comment by sajattack** [comment]
Still having troubles. Does it require pulseaudio?

**Comment by fabzzap** [comment]
No. At least, not directly. What kind of problem are you having?

**Comment by sajattack** [comment]
`attempt to connect to server failed`

**Comment by fabzzap** [comment]
Also here (Ubuntu 18.04) Portaudio does spit out quite a lot of messages when starting up, but those are not errors, the program works after those:

    ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
    ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
    ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
    ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
    ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
    ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
    Cannot connect to server socket err = No such file or directory
    Cannot connect to server request channel
    jack server is not running or cannot be started
    JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
    JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

**Comment by sajattack** [comment]
I do this and there is no output file
```
./wav-prg/cmdline/wav2prg buggyboy.wav -p buggyboy.prg
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm.c:2434:(snd_pcm_open_conf) type is not defined
ALSA lib pcm.c:2434:(snd_pcm_open_conf) type is not defined
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
```

I spun up a quick Ubuntu 18.04 container with lxc and there's no output at all. Then again, it doesn't have access to the sound card afaik.

**Comment by fabzzap** [comment]
Maybe it can't find the loaders. They are .so files that must be built in the `loaders` directory.

    ./wav-prg/cmdline/wav2prg -l
shows the list of detected loaders, which must not be empty. While in loaders directory,

    make -C ./wav-prg/loaders sos 
or

    make -C ./wav-prg/loaders sos LINUX64BITS=1
(the latter if you are using a 64-bit version of Linux) builds the known loaders.
By default, in Unix the executable searches for loaders is `/usr/lib/wav2prg`, but the Makefile has no `install` target that copies files there. You can copy the files manually, or you can change the search dir using the `-P` option. So I guess that, in your case, you should build the loaders, ensure the directory `buggyboydirectory` exists, then launch

    ./wav-prg/cmdline/wav2prg buggyboy.wav -P ./wav-prg/loaders -p buggyboydirectory
This info is a good candidate for addition to the README file

**Comment by sajattack** [comment]
Ok, it outputs a file now, but if I try to open said file in VICE, nothing happens

**Comment by fabzzap** [comment]
Can you please post the full console output?

**Comment by sajattack** [comment]
```
./wav-prg/cmdline/wav2prg buggyboy.wav -P ./wav-prg/loaders -p BUGGYBOY
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm.c:2434:(snd_pcm_open_conf) type is not defined
ALSA lib pcm.c:2434:(snd_pcm_open_conf) type is not defined
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
trying to get a sync using loader Default C64
got a pilot tone and a block at 473702
name BUGGY BOY start 828 end 1020
Checked checksum from 544785 to 544785
computed checksum 0 (00) loaded checksum 0 (00) correct
Program ends at 544325, 192 bytes long, correct
trying to get a sync using loader Default C64 (2nd copy)
got a pilot tone and a block at 558518
name BUGGY BOY start 828 end 1020
Checked checksum from 629601 to 629601
computed checksum 0 (00) loaded checksum 0 (00) correct
Program ends at 629141, 192 bytes long, correct
trying to get a sync using loader Kernal data chunk
got a pilot tone and a block at 740359
name BUGGY BOY start 52297 end 52473
Checked checksum from 813507 to 813507
computed checksum 0 (00) loaded checksum 0 (00) correct
Program ends at 813047, 176 bytes long, correct
trying to get a sync using loader Kernal data chunk (2nd copy)
got a pilot tone and a block at 818567
name BUGGY BOY start 52297 end 52473
Checked checksum from 891715 to 891715
computed checksum 0 (00) loaded checksum 0 (00) correct
Program ends at 891255, 176 bytes long, correct
trying to get a sync using loader Default C64
```

**Comment by fabzzap** [comment]
OK, this means that things work. wav2prg needs a loader for each format to support it, and, in your case, it seems that there is no loader for the format Buggy Boy was saved. I guess a small PRG file (178 bytes) is saved, that only contains the loader code and not the game itself. If you can share the WAV file, I can try and see whether a loader can be made.
In any case, the main problem is that the README file does not mention that the loader files also need to be built. I'll try to find some time to fix that.

**Comment by sajattack** [comment]
I used this tap and converted to wav with audiotap, since I wasn't sure if wav-prg supported wav only.
http://www.planetemu.net/rom/commodore-c64-games-tap/buggy-boy-1987-elite

**Comment by fabzzap** [comment]
wav-prg also supports TAP files, so converting to WAV isn't necessary, but it works. I'll try that TAP file then

**Comment by fabzzap** [comment]
This did the trick

    ./wav-prg/cmdline/wav2prg -P wav-prg/loaders -s Novaload\ Normal ~/Buggy\ Boy\ \(1987\)\(Elite\).tap -p someoutputdir
Basically, some formats are auto-detected, others are supported but must be specified on the command line. The TAP is in Novaload format, which falls into the latter case.
Something I have intended to do for ages is to add a mode where all known formats are tried. Since it is a major feat, I never got along to actually do it.

**Comment by sajattack** [comment]
Thanks.
